baseURL = "https://webhost.co.id/"
languageCode = "id-id"
title = "Web Host Indonesia"

[menu]
[[menu.main]]
    name = "Layanan"
    url = "/layanan/"
    weight = -110

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = -100

[[menu.main]]
    name = "Tentang"
    url = "/about/"
    weight = -90
[[menu.main]]
    name = "Kontak"
    url = "/kontak/"
    weight = -80